/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubesphere.io/api/pvcviewer/v1alpha1"
)

// PVCViewerLister helps list PVCViewers.
// All objects returned here must be treated as read-only.
type PVCViewerLister interface {
	// List lists all PVCViewers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.PVCViewer, err error)
	// PVCViewers returns an object that can list and get PVCViewers.
	PVCViewers(namespace string) PVCViewerNamespaceLister
	PVCViewerListerExpansion
}

// pVCViewerLister implements the PVCViewerLister interface.
type pVCViewerLister struct {
	indexer cache.Indexer
}

// NewPVCViewerLister returns a new PVCViewerLister.
func NewPVCViewerLister(indexer cache.Indexer) PVCViewerLister {
	return &pVCViewerLister{indexer: indexer}
}

// List lists all PVCViewers in the indexer.
func (s *pVCViewerLister) List(selector labels.Selector) (ret []*v1alpha1.PVCViewer, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PVCViewer))
	})
	return ret, err
}

// PVCViewers returns an object that can list and get PVCViewers.
func (s *pVCViewerLister) PVCViewers(namespace string) PVCViewerNamespaceLister {
	return pVCViewerNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// PVCViewerNamespaceLister helps list and get PVCViewers.
// All objects returned here must be treated as read-only.
type PVCViewerNamespaceLister interface {
	// List lists all PVCViewers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.PVCViewer, err error)
	// Get retrieves the PVCViewer from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.PVCViewer, error)
	PVCViewerNamespaceListerExpansion
}

// pVCViewerNamespaceLister implements the PVCViewerNamespaceLister
// interface.
type pVCViewerNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all PVCViewers in the indexer for a given namespace.
func (s pVCViewerNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.PVCViewer, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PVCViewer))
	})
	return ret, err
}

// Get retrieves the PVCViewer from the indexer for a given namespace and name.
func (s pVCViewerNamespaceLister) Get(name string) (*v1alpha1.PVCViewer, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("pvcviewer"), name)
	}
	return obj.(*v1alpha1.PVCViewer), nil
}
