/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	pvcv1 "kubesphere.io/api/pvc/v1"
)

// FakePVCCloneRequests implements PVCCloneRequestInterface
type FakePVCCloneRequests struct {
	Fake *FakePvcV1
	ns   string
}

var pvcclonerequestsResource = schema.GroupVersionResource{Group: "pvc.ecpaas.io", Version: "v1", Resource: "pvcclonerequests"}

var pvcclonerequestsKind = schema.GroupVersionKind{Group: "pvc.ecpaas.io", Version: "v1", Kind: "PVCCloneRequest"}

// Get takes name of the pVCCloneRequest, and returns the corresponding pVCCloneRequest object, and an error if there is any.
func (c *FakePVCCloneRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *pvcv1.PVCCloneRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pvcclonerequestsResource, c.ns, name), &pvcv1.PVCCloneRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pvcv1.PVCCloneRequest), err
}

// List takes label and field selectors, and returns the list of PVCCloneRequests that match those selectors.
func (c *FakePVCCloneRequests) List(ctx context.Context, opts v1.ListOptions) (result *pvcv1.PVCCloneRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pvcclonerequestsResource, pvcclonerequestsKind, c.ns, opts), &pvcv1.PVCCloneRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &pvcv1.PVCCloneRequestList{ListMeta: obj.(*pvcv1.PVCCloneRequestList).ListMeta}
	for _, item := range obj.(*pvcv1.PVCCloneRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pVCCloneRequests.
func (c *FakePVCCloneRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pvcclonerequestsResource, c.ns, opts))

}

// Create takes the representation of a pVCCloneRequest and creates it.  Returns the server's representation of the pVCCloneRequest, and an error, if there is any.
func (c *FakePVCCloneRequests) Create(ctx context.Context, pVCCloneRequest *pvcv1.PVCCloneRequest, opts v1.CreateOptions) (result *pvcv1.PVCCloneRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pvcclonerequestsResource, c.ns, pVCCloneRequest), &pvcv1.PVCCloneRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pvcv1.PVCCloneRequest), err
}

// Update takes the representation of a pVCCloneRequest and updates it. Returns the server's representation of the pVCCloneRequest, and an error, if there is any.
func (c *FakePVCCloneRequests) Update(ctx context.Context, pVCCloneRequest *pvcv1.PVCCloneRequest, opts v1.UpdateOptions) (result *pvcv1.PVCCloneRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pvcclonerequestsResource, c.ns, pVCCloneRequest), &pvcv1.PVCCloneRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pvcv1.PVCCloneRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePVCCloneRequests) UpdateStatus(ctx context.Context, pVCCloneRequest *pvcv1.PVCCloneRequest, opts v1.UpdateOptions) (*pvcv1.PVCCloneRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pvcclonerequestsResource, "status", c.ns, pVCCloneRequest), &pvcv1.PVCCloneRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pvcv1.PVCCloneRequest), err
}

// Delete takes name of the pVCCloneRequest and deletes it. Returns an error if one occurs.
func (c *FakePVCCloneRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pvcclonerequestsResource, c.ns, name), &pvcv1.PVCCloneRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePVCCloneRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pvcclonerequestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &pvcv1.PVCCloneRequestList{})
	return err
}

// Patch applies the patch and returns the patched pVCCloneRequest.
func (c *FakePVCCloneRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *pvcv1.PVCCloneRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pvcclonerequestsResource, c.ns, name, pt, data, subresources...), &pvcv1.PVCCloneRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pvcv1.PVCCloneRequest), err
}
