/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	pvcv1 "kubesphere.io/api/pvc/v1"
	versioned "kubesphere.io/kubesphere/pkg/client/clientset/versioned"
	internalinterfaces "kubesphere.io/kubesphere/pkg/client/informers/externalversions/internalinterfaces"
	v1 "kubesphere.io/kubesphere/pkg/client/listers/pvc/v1"
)

// PVCCloneRequestInformer provides access to a shared informer and lister for
// PVCCloneRequests.
type PVCCloneRequestInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PVCCloneRequestLister
}

type pVCCloneRequestInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPVCCloneRequestInformer constructs a new informer for PVCCloneRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPVCCloneRequestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPVCCloneRequestInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPVCCloneRequestInformer constructs a new informer for PVCCloneRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPVCCloneRequestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PvcV1().PVCCloneRequests(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PvcV1().PVCCloneRequests(namespace).Watch(context.TODO(), options)
			},
		},
		&pvcv1.PVCCloneRequest{},
		resyncPeriod,
		indexers,
	)
}

func (f *pVCCloneRequestInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPVCCloneRequestInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pVCCloneRequestInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pvcv1.PVCCloneRequest{}, f.defaultInformer)
}

func (f *pVCCloneRequestInformer) Lister() v1.PVCCloneRequestLister {
	return v1.NewPVCCloneRequestLister(f.Informer().GetIndexer())
}
