/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1 "kubesphere.io/api/pvc/v1"
)

// PVCCloneRequestLister helps list PVCCloneRequests.
// All objects returned here must be treated as read-only.
type PVCCloneRequestLister interface {
	// List lists all PVCCloneRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.PVCCloneRequest, err error)
	// PVCCloneRequests returns an object that can list and get PVCCloneRequests.
	PVCCloneRequests(namespace string) PVCCloneRequestNamespaceLister
	PVCCloneRequestListerExpansion
}

// pVCCloneRequestLister implements the PVCCloneRequestLister interface.
type pVCCloneRequestLister struct {
	indexer cache.Indexer
}

// NewPVCCloneRequestLister returns a new PVCCloneRequestLister.
func NewPVCCloneRequestLister(indexer cache.Indexer) PVCCloneRequestLister {
	return &pVCCloneRequestLister{indexer: indexer}
}

// List lists all PVCCloneRequests in the indexer.
func (s *pVCCloneRequestLister) List(selector labels.Selector) (ret []*v1.PVCCloneRequest, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.PVCCloneRequest))
	})
	return ret, err
}

// PVCCloneRequests returns an object that can list and get PVCCloneRequests.
func (s *pVCCloneRequestLister) PVCCloneRequests(namespace string) PVCCloneRequestNamespaceLister {
	return pVCCloneRequestNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// PVCCloneRequestNamespaceLister helps list and get PVCCloneRequests.
// All objects returned here must be treated as read-only.
type PVCCloneRequestNamespaceLister interface {
	// List lists all PVCCloneRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.PVCCloneRequest, err error)
	// Get retrieves the PVCCloneRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.PVCCloneRequest, error)
	PVCCloneRequestNamespaceListerExpansion
}

// pVCCloneRequestNamespaceLister implements the PVCCloneRequestNamespaceLister
// interface.
type pVCCloneRequestNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all PVCCloneRequests in the indexer for a given namespace.
func (s pVCCloneRequestNamespaceLister) List(selector labels.Selector) (ret []*v1.PVCCloneRequest, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.PVCCloneRequest))
	})
	return ret, err
}

// Get retrieves the PVCCloneRequest from the indexer for a given namespace and name.
func (s pVCCloneRequestNamespaceLister) Get(name string) (*v1.PVCCloneRequest, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("pvcclonerequest"), name)
	}
	return obj.(*v1.PVCCloneRequest), nil
}
