/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	pvcviewerv1alpha1 "kubesphere.io/api/pvcviewer/v1alpha1"
	versioned "kubesphere.io/kubesphere/pkg/client/clientset/versioned"
	internalinterfaces "kubesphere.io/kubesphere/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubesphere.io/kubesphere/pkg/client/listers/pvcviewer/v1alpha1"
)

// PVCViewerInformer provides access to a shared informer and lister for
// PVCViewers.
type PVCViewerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PVCViewerLister
}

type pVCViewerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPVCViewerInformer constructs a new informer for PVCViewer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPVCViewerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPVCViewerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPVCViewerInformer constructs a new informer for PVCViewer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPVCViewerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PvcviewerV1alpha1().PVCViewers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PvcviewerV1alpha1().PVCViewers(namespace).Watch(context.TODO(), options)
			},
		},
		&pvcviewerv1alpha1.PVCViewer{},
		resyncPeriod,
		indexers,
	)
}

func (f *pVCViewerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPVCViewerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pVCViewerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pvcviewerv1alpha1.PVCViewer{}, f.defaultInformer)
}

func (f *pVCViewerInformer) Lister() v1alpha1.PVCViewerLister {
	return v1alpha1.NewPVCViewerLister(f.Informer().GetIndexer())
}
