/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	clustersyncv1 "kubesphere.io/api/clustersync/v1"
)

// FakeOperatorConfigs implements OperatorConfigInterface
type FakeOperatorConfigs struct {
	Fake *FakeClustersyncV1
	ns   string
}

var operatorconfigsResource = schema.GroupVersionResource{Group: "clustersync.ecpaas.io", Version: "v1", Resource: "operatorconfigs"}

var operatorconfigsKind = schema.GroupVersionKind{Group: "clustersync.ecpaas.io", Version: "v1", Kind: "OperatorConfig"}

// Get takes name of the operatorConfig, and returns the corresponding operatorConfig object, and an error if there is any.
func (c *FakeOperatorConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *clustersyncv1.OperatorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(operatorconfigsResource, c.ns, name), &clustersyncv1.OperatorConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersyncv1.OperatorConfig), err
}

// List takes label and field selectors, and returns the list of OperatorConfigs that match those selectors.
func (c *FakeOperatorConfigs) List(ctx context.Context, opts v1.ListOptions) (result *clustersyncv1.OperatorConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(operatorconfigsResource, operatorconfigsKind, c.ns, opts), &clustersyncv1.OperatorConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &clustersyncv1.OperatorConfigList{ListMeta: obj.(*clustersyncv1.OperatorConfigList).ListMeta}
	for _, item := range obj.(*clustersyncv1.OperatorConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested operatorConfigs.
func (c *FakeOperatorConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(operatorconfigsResource, c.ns, opts))

}

// Create takes the representation of a operatorConfig and creates it.  Returns the server's representation of the operatorConfig, and an error, if there is any.
func (c *FakeOperatorConfigs) Create(ctx context.Context, operatorConfig *clustersyncv1.OperatorConfig, opts v1.CreateOptions) (result *clustersyncv1.OperatorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(operatorconfigsResource, c.ns, operatorConfig), &clustersyncv1.OperatorConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersyncv1.OperatorConfig), err
}

// Update takes the representation of a operatorConfig and updates it. Returns the server's representation of the operatorConfig, and an error, if there is any.
func (c *FakeOperatorConfigs) Update(ctx context.Context, operatorConfig *clustersyncv1.OperatorConfig, opts v1.UpdateOptions) (result *clustersyncv1.OperatorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(operatorconfigsResource, c.ns, operatorConfig), &clustersyncv1.OperatorConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersyncv1.OperatorConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOperatorConfigs) UpdateStatus(ctx context.Context, operatorConfig *clustersyncv1.OperatorConfig, opts v1.UpdateOptions) (*clustersyncv1.OperatorConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(operatorconfigsResource, "status", c.ns, operatorConfig), &clustersyncv1.OperatorConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersyncv1.OperatorConfig), err
}

// Delete takes name of the operatorConfig and deletes it. Returns an error if one occurs.
func (c *FakeOperatorConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(operatorconfigsResource, c.ns, name), &clustersyncv1.OperatorConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOperatorConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(operatorconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &clustersyncv1.OperatorConfigList{})
	return err
}

// Patch applies the patch and returns the patched operatorConfig.
func (c *FakeOperatorConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *clustersyncv1.OperatorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(operatorconfigsResource, c.ns, name, pt, data, subresources...), &clustersyncv1.OperatorConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersyncv1.OperatorConfig), err
}
